"""Read/write PSMC output format (.psmc files)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np


def read_psmc_output(path: str | Path) -> list[dict[str, Any]]:
    """Read a PSMC output file and extract results per iteration round.

    Parameters
    ----------
    path : str or Path
        Path to ``.psmc`` output file.

    Returns
    -------
    list of dict
        One dict per EM round, each containing:
        - ``"round"``: iteration number
        - ``"log_likelihood"``: log P(data)
        - ``"theta"``: θ₀
        - ``"rho"``: ρ₀
        - ``"time"``: array of t_k values
        - ``"lambda"``: array of λ_k values
        - ``"pi"``: array of π_k values
        - ``"sigma"``: array of σ_k values
        - ``"post_sigma"``: array of posterior σ_k values
    """
    path = Path(path)
    rounds: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None
    rs_rows: list[list[float]] = []

    def _flush_round():
        nonlocal current, rs_rows
        if current is not None and rs_rows:
            arr = np.array(rs_rows)
            current["time"] = arr[:, 1]
            current["lambda"] = arr[:, 2]
            current["pi"] = arr[:, 3]
            current["sigma"] = arr[:, 4]
            current["post_sigma"] = arr[:, 5]
            rounds.append(current)
        current = None
        rs_rows = []

    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("CC"):
                continue
            parts = line.split("\t")
            tag = parts[0]

            if tag == "RD":
                _flush_round()
                current = {"round": int(parts[1])}
                rs_rows = []
            elif tag == "LK" and current is not None:
                current["log_likelihood"] = float(parts[1])
            elif tag == "TR" and current is not None:
                current["theta"] = float(parts[1])
                current["rho"] = float(parts[2])
            elif tag == "RS" and current is not None:
                rs_rows.append([float(x) for x in parts[1:]])
            elif tag == "PA" and current is not None:
                pa_parts = parts[1].split()
                current["pattern"] = pa_parts[0]
                current["params"] = np.array([float(x) for x in pa_parts[1:]])

    _flush_round()
    return rounds


def write_psmc_output(
    path: str | Path,
    rounds: list[dict[str, Any]],
    pattern: str = "",
    metadata: dict[str, str] | None = None,
) -> None:
    """Write PSMC results in the standard .psmc output format.

    Parameters
    ----------
    path : str or Path
        Output file path.
    rounds : list of dict
        Results per round (same format as ``read_psmc_output`` returns).
    pattern : str
        Parameter pattern string.
    metadata : dict, optional
        Additional metadata lines (key-value pairs written as MM lines).
    """
    path = Path(path)
    with open(path, "w") as f:
        f.write("CC\n")
        f.write("CC\tGenerated by smckit\n")
        f.write("CC\n")
        if metadata:
            for k, v in metadata.items():
                f.write(f"MM\t{k}: {v}\n")

        for rd in rounds:
            f.write(f"RD\t{rd['round']}\n")
            if "log_likelihood" in rd:
                f.write(f"LK\t{rd['log_likelihood']:.6f}\n")
            if "Q0" in rd and "Q1" in rd:
                f.write(f"QD\t{rd['Q0']:.6f} -> {rd['Q1']:.6f}\n")
            if "theta" in rd and "rho" in rd:
                f.write(f"TR\t{rd['theta']:.6f}\t{rd['rho']:.6f}\n")
            if "max_t" in rd:
                f.write(f"MT\t{rd['max_t']:.6f}\n")

            if "time" in rd and "lambda" in rd:
                n_states = len(rd["time"])
                pi = rd.get("pi", np.zeros(n_states))
                sigma = rd.get("sigma", np.zeros(n_states))
                post_sigma = rd.get("post_sigma", np.zeros(n_states))
                for k in range(n_states):
                    f.write(
                        f"RS\t{k}\t{rd['time'][k]:.6f}\t{rd['lambda'][k]:.6f}"
                        f"\t{pi[k]:.6f}\t{sigma[k]:.6f}\t{post_sigma[k]:.6f}\n"
                    )

            if "params" in rd:
                params_str = " ".join(f"{p:.9f}" for p in rd["params"])
                f.write(f"PA\t{pattern} {params_str}\n")
            f.write("//\n")
